server:
  port: 8086

spring:
  application:
    name: auth-service
  cloud:
    consul:
          discovery:
            healthCheckInterval: 15s
            hostname: localhost
            enabled: true
            register: true
            health-check-path: /actuator/health

management:
  endpoints:
    web:
      exposure:
        include: "*"
