server:
  port: 8086

spring:
  application:
    name: auth-service


  #Questo uri viene usato per validare il token jwt in arrivo dal gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/realms/springboot-microservice-realm/protocol/openid-connect/certs


eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true