spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: wineGroup
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.wine.microservice.dto"

#Questo uri viene usato per validare il token jwt in arrivo dal gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/realms/springboot-microservice-realm/protocol/openid-connect/certs

  cloud:
    consul:
      discovery:
        hostname: localhost
        enabled: true
        register: true
        health-check-path: /actuator/health