version: "3.8"
services:
  postgres-wine-query:
    image: 'postgres:latest'
    container_name: postgres-wine-query
    environment:
      POSTGRES_DB: wine-query-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - wine-query-data:/var/lib/postgresql/data
    restart: always

  postgres-wine-command:
    image: 'postgres:latest'
    container_name: postgres-wine-command
    environment:
      POSTGRES_DB: wine-command-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - wine-command-data:/var/lib/postgresql/data
    restart: always

  postgres-ai-service:
    image: 'postgres:latest'
    container_name: postgres-ai-service
    environment:
      POSTGRES_DB: ai-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ai-service-data:/var/lib/postgresql/data
    restart: always


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres-wine-query
      - postgres-wine-command
      - postgres-ai-service

volumes:
  wine-query-data:
  wine-command-data:
  ai-service-data:
  pgadmin-data:





