version: "3.8"
services:
  postgres-wine:
    image: 'postgres:latest'
    container_name: postgres-wine
    environment:
      POSTGRES_DB: wine-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - wine-data:/var/lib/postgresql/data
    restart: always


  postgres-ai-service:
    image: 'postgres:latest'
    container_name: postgres-ai-service
    environment:
      POSTGRES_DB: ai-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ai-service-data:/var/lib/postgresql/data
    restart: always


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres-wine
      - postgres-ai-service

volumes:
  wine-data:
  ai-service-data:
  pgadmin-data:





