server:
  port: 8085

spring:
  cloud:
    gateway:
      routes:
        - id: wine-command
          uri: lb://wine-command
          predicates:
            - Path=/wine-command/**

        - id: wine-query
          uri: lb://wine-query
          predicates:
            - Path=/wine/**

        - id: ai-service
          uri: lb://ai-service
          predicates:
            - Path=/ai/**

  application:
    name: gateway-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/springboot-microservice-realm

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true