#Questo uri viene usato per validare il token jwt in arrivo dal gateway
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/realms/springboot-microservice-realm/protocol/openid-connect/certs
  cloud:
    consul:
      discovery:
        hostname: localhost
        enabled: true
        register: true
        health-check-path: /actuator/health

    function:
      definition: toUpperCase

